DROP TABLE IF EXISTS `mytable`;
CREATE TABLE `mytable` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `other` VARCHAR(255) NOT NULL,

    PRIMARY KEY (`id`)
);
